version: '3.8'

services:
  app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - .:/app
    command: python app.py
